# Generated by Django 2.0.2 on 2018-03-05 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
    sql=['ALTER TABLE collection_book MODIFY title VARCHAR(255) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci',
         'ALTER TABLE collection_author MODIFY name VARCHAR(255) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci'],
    reverse_sql=['ALTER TABLE collection_book MODIFY title VARCHAR(255)',
                 'ALTER TABLE collection_author MODIFY name VARCHAR(255)'])
    ]
