# Generated by Django 2.0.2 on 2018-03-11 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 24, 18, 21, 48, 564496)),
        ),
    ]
