# Generated by Django 2.0.2 on 2018-03-13 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20180310_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 27, 2, 0, 55, 820753)),
        ),
    ]
