# Generated by Django 2.0.2 on 2018-03-13 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20180313_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 27, 2, 1, 14, 75616)),
        ),
    ]
