# Generated by Django 2.0.2 on 2018-03-13 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20180313_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_loan',
            name='date_in',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book_loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 27, 2, 2, 6, 999432)),
        ),
    ]
