# Generated by Django 2.0.2 on 2018-03-13 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_auto_20180313_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower',
            old_name='bname_first',
            new_name='bname',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='bname_last',
        ),
        migrations.AlterField(
            model_name='book_loan',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 27, 13, 49, 57, 987732)),
        ),
    ]
